package Task::BeLike::SHARYANTO::Authored;
# ABSTRACT: Install all modules authored by SHARYANTO on CPAN

# note: list of pkgs generated by generate-pkg-lists-for-tbsha

# VERSION

=head1 DESCRIPTION

This task will install all modules authored by SHARYANTO currently on CPAN.
Excluded are other Task::* modules, or modules already deletd from CPAN.

=pkgroup Included modules

=pkg Acme::CPANAuthors::Female

=pkg Acme::CPANAuthors::Indonesian

=pkg Any::Renderer::Pretty::Console

=pkg Any::Renderer::Pretty::HTML

=pkg App::HTMLCalendarMonth::Indonesia

=pkg App::OrgUtils

=pkg App::SerializeUtils

=pkg App::UniqFiles

=pkg App::perlmv

=pkg Array::Find

=pkg Array::Functions::Undoable

=pkg Array::Iterator

=pkg Bench

=pkg Builtin::Logged

=pkg Business::ID::NIK

=pkg Business::ID::NOPPBB

=pkg Business::ID::NPWP

=pkg Business::ID::SIM

=pkg Calendar::Indonesia::Holiday

=pkg Config::Ini::OnDrugs

=pkg Data::Dump::Ala::SHARYANTO

=pkg Data::Dump::OneLine

=pkg Data::Dump::PHP

=pkg Data::Dump::Partial

=pkg Data::Dump::Ruby

=pkg Data::Format::Pretty

=pkg Data::Format::Pretty::Console

=pkg Data::Format::Pretty::HTML

=pkg Data::Format::Pretty::JSON

=pkg Data::Format::Pretty::PHP

=pkg Data::Format::Pretty::PHPSerialization

=pkg Data::Format::Pretty::Perl

=pkg Data::Format::Pretty::Ruby

=pkg Data::Format::Pretty::YAML

=pkg Data::ModeMerge

=pkg Data::Sah

=pkg Data::Sah::Util

=pkg Devel::EndStats

=pkg File::RsyBak

=pkg File::Slurp::Shortcuts

=pkg Finance::Bank::ID::BCA

=pkg Finance::Bank::ID::Mandiri

=pkg Gepok

=pkg Git::Bunch

=pkg HTTP::Daemon::UNIX

=pkg LWP::Protocol::http::SocketUnixAlt

=pkg Language::Expr

=pkg Ledger::Parser

=pkg Lingua::EN::Number::Format::MixWithWords

=pkg Lingua::ID::Number::Format::MixWithWords

=pkg Lingua::ID::Nums2Words

=pkg Lingua::ID::Words2Nums

=pkg Lingua::ZH::PinyinConvert::ID

=pkg Locale::ID::GuessGender::FromFirstName

=pkg Locale::ID::Locality

=pkg Locale::ID::Province

=pkg Log::Any::Adapter::Callback

=pkg Log::Any::Adapter::ScreenColoredLevel

=pkg Log::Any::App

=pkg Log::Dispatch::Dir

=pkg Object::BlankStr

=pkg Object::NulStr

=pkg Object::SpaceBackStr

=pkg Org::Parser

=pkg Org::To::HTML

=pkg Org::To::Pod

=pkg Org::To::Text

=pkg Parse::Netstat

=pkg Parse::Number::EN

=pkg Parse::Number::ID

=pkg Parse::PhoneNumber::ID

=pkg Passwd::Unix::Alt

=pkg Perinci

=pkg Perinci::Access::HTTP::Server

=pkg Perinci::BashComplete

=pkg Perinci::CmdLine

=pkg Perinci::Examples

=pkg Perinci::Gen::ForModule

=pkg Perinci::Object

=pkg Perinci::Sub::ConvertArgs::Array

=pkg Perinci::Sub::DepChecker

=pkg Perinci::Sub::Gen::AccessTable

=pkg Perinci::Sub::GetArgs::Argv

=pkg Perinci::Sub::GetArgs::Array

=pkg Perinci::Sub::Wrapper

=pkg Perinci::Sub::property::drops_privilege

=pkg Perinci::Sub::property::result_postfilter

=pkg Perinci::Sub::property::retry

=pkg Perinci::Sub::property::timeout

=pkg Perinci::To::HTML

=pkg Perinci::To::POD

=pkg Perinci::To::Text

=pkg Perinci::Use

=pkg Pod::Weaver::Plugin::Perinci

=pkg Process::KillTree

=pkg RSS::From::Forum::vBulletin

=pkg Riap

=pkg Rinci

=pkg SHARYANTO::String::Util

=pkg SHARYANTO::Utils

=pkg Serabi

=pkg Setup

=pkg Setup::File

=pkg Setup::File::Symlink

=pkg Setup::Multi

=pkg Setup::Test

=pkg Setup::Text::Snippet

=pkg Setup::Unix::User

=pkg Test::Setup

=pkg Text::sprintfn

=pkg WWW::GudangAPI

=cut

1;
